### ISSUE TITLE
Unable to override throughput requirement when building gp2 AMI builds

### ISSUE THREAD

**Issue by abhay-krishna** [kubernetes-sigs/image-builder#1102]
The packer.json for AMI builds has a [throughput field](https://github.com/kubernetes-sigs/image-builder/blob/master/images/capi/packer/ami/packer.json#L20) in the block device mappings section with a default value of 125, but this field is valid only for gp3 volumes.  I tried building an Ubuntu gp2 AMI by overriding the throughput from a different JSON var-file (ami.json below) by setting it to `""` or even `null` , but in both cases the build failed with the following error message.
```
Throughput is not available for device /dev/sda1
```
Only when I removed that field from image-builder's packer.json did the build proceed past this point. But removal also doesn't seem to be a permanent solution because now there's no way of passing throughput in if I do want to build a gp3 volume. Should I be overriding the default value and/or presence of throughput field in some other way?

**What steps did you take and what happened:**
```
PACKER_FLAGS="-force" PACKER_LOG=1 PACKER_LOG_PATH=$PWD/packer.log PACKER_VAR_FILES=$PWD/ami.json make -C $PWD/image-builder/images/capi build-ami-ubuntu-2004
```
Here is my var-file with some override vars
```
// ami.json
{
  "ami_filter_name": "ubuntu/images/*ubuntu-focal-20.04-amd64-server-*",
  "ami_filter_owners": "amazon",
  "ami_regions": "us-east-1",
  "aws_region": "us-east-1",
  "builder_instance_type": "t3.large",
  "root_device_name": "/dev/sda1",
  "throughput": "",
  "volume_size": "16",
  "volume_type": "gp2",
}
```

**What did you expect to happen:**
I am able to override throughput to a non-empty/non-null value and use it to build a gp3 AMI. Similarly, I expected that setting throughput to `""` or `null` in the ami.json would nullify the throughput input and successfully build a gp2 (or any non-gp3, for that matter) AMI.

Maybe I am doing something wrong or this truly is a limitation. Appreciate any help on this!

**Environment:**
I built this on an Ubuntu 20.04 EC2 instance.

/kind bug

**Comment by kkeshavamurthy** [comment]
@abhay-krishna Looks like [throughput](https://developer.hashicorp.com/packer/plugins/builders/amazon/ebs#throughput) variable should only be provided if `gp3` volumes are being used. 
If you'd like to use `gp2`, I suggest you run a jq command to remove the `throughput` var from the builder config. Since packer does not allow conditionals in the builder config, incompatibilities like this are quite common. There are similar issues for [vsphere export](https://github.com/kubernetes-sigs/image-builder/blob/master/images/capi/scripts/ci-ova.sh#L69), azure [custom rg](https://github.com/kubernetes-sigs/image-builder/pull/1066) etc.

**Comment by abhay-krishna** [comment]
Yeah, removing using `jq` is my current workaround, thanks for confirming!
