### ISSUE TITLE
Failed Build QEMU Image

### ISSUE THREAD

**Issue by iputra** [kubernetes-sigs/image-builder#238]
Hi

I'm trying to build qemu image by using image-builder for cluster-api provider openstack, but I'm getting error in provisioning with ansible. The following error is like this :

```
. . .
    ubuntu-1804: PLAY [all] *********************************************************************
    ubuntu-1804:
    ubuntu-1804: TASK [Gathering Facts] *********************************************************
    ubuntu-1804: ok: [default]
    ubuntu-1804:
    ubuntu-1804: TASK [setup : Put templated sources.list in place] *****************************
    ubuntu-1804: fatal: [default]: FAILED! => {"changed": false, "checksum": "963e5f098c598950964617d096a2ba51d2c09734", "msg": "Destination /etc/apt not writable"}
    ubuntu-1804:
    ubuntu-1804: PLAY RECAP *********************************************************************
    ubuntu-1804: default                    : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
    ubuntu-1804:
==> ubuntu-1804: Provisioning step had errors: Running the cleanup provisioner, if present...
==> ubuntu-1804: Deleting output directory...
Build 'ubuntu-1804' errored: Error executing Ansible: Non-zero exit status: exit status 2
==> Some builds didn't complete successfully and had errors:
--> ubuntu-1804: Error executing Ansible: Non-zero exit status: exit status 2
==> Builds finished but no artifacts were created.
make: *** [build-qemu-ubuntu-1804] Error 1
. . .
```

**Comment by snicholas** [comment]
Hi, I'm experiencing the same problem. Tried also with older tags, but same problem. 
I've tried on ubuntu 18.04. Ansible version is 2.8.0 and packer should be 1.5.2.

**Comment by snicholas** [comment]
I resolved by adding my user to the kvm group
`sudo usermod -a -G kvm <yourusername>`
and (even if I'm not sure it is really usefull)
`sudo chown root:kvm /dev/kvm`
then exit and log back in to make the change take place.
After that run 
`make build-qemu-ubuntu-1804`
as the normal user (non root). Hope this help out!

**Comment by iputra** [comment]
> Hi, I'm experiencing the same problem. Tried also with older tags, but same problem.
> I've tried on ubuntu 18.04. Ansible version is 2.8.0 and packer should be 1.5.2.
> @iputra did you rn the make command as root or normal user?

Yup, I also tried with older tags, but same problem.
I have tried as make command as root and also normal user still got the same issue.

**Comment by iputra** [comment]
> I resolved by adding my user to the kvm group
> `sudo usermod -a -G kvm <yourusername>`
> and (even if I'm not sure it is really usefull)
> `sudo chown root:kvm /dev/kvm`
> then exit and log back in to make the change take place.
> After that run
> `make build-qemu-ubuntu-1804`
> as the normal user (non root). Hope this help out!

I just tried it and this is fix the issue.
Thanks @snicholas for your help.

**Comment by codenrhoden** [comment]
I'm glad a solution was found, but I really think that solution should be added to the docs, otherwise more people will trip over the same issue.

**Comment by hidekazuna** [comment]
> I'm glad a solution was found, but I really think that solution should be added to the docs, otherwise more people will trip over the same issue.

I will add to the docs soon!

**Comment by carstenkoester** [comment]
Found this issue, naturally, *after* running into the problem described here and doing all the troubleshooting -- but then decided to put some additional analysis here anyway, just in case it turns out to be useful.

- Ansible communicates not directly with the VM, but with Packer's SSH communicator (that, by default, runs as the user which Packer is invoked as).
- Packer's SSH communicator communicates with the VM, using the username and password that are specified in packer.json (`builder`/`builder`) as per `packer/qemu/packer.json`.

```
Ansible ------> SSH communicator -----> VM

          ^                        ^
          |                        |
      Random TCP               Random TCP
       port #1,                  port #2,
    invoking user           ssh_username as per
                            communicator config
```

Random TCP port #2 can be seen in Packer output logs (eg: `Found port for communicator (SSH, WinRM, etc): 2404`); TCP port #1 can't be seen in standard logs but can be seen in the Ansible inventory that is created while the Ansible provisioner runs:

```
# cat /tmp/packer-provisioner-ansible*
default ansible_host=127.0.0.1 ansible_user=root ansible_port=38259
```

Now - when Packer is run as root, then Ansible communicates with the provisioner as root. Ansible seems to realize that `ansible_ssh_user == become_user` and thus skip the privilege escalation step, thinking it is already logged in as root. From the VM's perspective, though, it is logged in as "builder".

**Solution #1**, as described here, is to not run as root. If Packer runs as non-root, then the Ansible<->Communicator session will be as non-root, and Ansible realizes it will need to "do work" in order to become root.

**Solution #2** is to override the provisioner user as per <https://www.packer.io/docs/provisioners/ansible/#user>.

```
--- a/images/capi/packer/qemu/packer.json
+++ b/images/capi/packer/qemu/packer.json
@@ -76,6 +76,7 @@
     {
       "type": "ansible",
       "playbook_file": "./ansible/node.yml",
+      "user": "builder",
       "ansible_env_vars": [
         "ANSIBLE_SSH_ARGS='{{user `existing_ansible_ssh_args`}} -o IdentitiesOnly=yes'",
         "ANSIBLE_REMOTE_TEMP='/tmp/.ansible/'"
```

Doing so forces the outgoing SSH session from Ansible to use the specified username (instead of the invoking username), and thus again forces Ansible into actually "doing work" for privilege escalation. Note that the username specified there need not *actually* exist - it's purely a virtual construct with Packer's SSH helper.


Solution #1 (running as non root) is probably the better solution from a "best practices" point of view. However, solution #2 might be useful when Packer needs to be run as root or is invoked in an environment that tends to run by root as default, such as some Jenkins pipeline workers.
