### ISSUE TITLE
"advanced" partitioning layouts

### ISSUE THREAD

**Issue by MaxRink** [kubernetes-sigs/image-builder#257]
Currently CAPI-Images build from ISOs use a very simplistic partition layout which makes them more prone for certain failures, like an overfull /var and /var/log. 
We mitigated that by adding /var and /var/log partitions, but this currently breaks the cleanup-steps in sysprep as /var/log cant be deleted at this point.
We've also build autoexpansion of the OS to the disksize specified in vmware/OpenStack.
Would there be a general Interest to include such things in Image-builder, because if so i would invest time to refactor them a bit.

**Comment by detiber** [comment]
@MaxRink my initial thoughts are that yes, we should likely support more advanced partitioning layouts, especially as we are looking to support things like using a separate volume for etcd, and trying to take advantage of ephemeral disks where possible for performance reasons.

I suspect @voor, @codenrhoden, @randomvariable, @CecileRobertMichon, and possibly others might have additional thoughts. 

/cc @voor @codenrhoden @randomvariable @CecileRobertMichon

**Comment by voor** [comment]
So I think the idea here was that these new partitions would exist at creation time of the actual instance as provided by the underlying IAAS rather than at time of the base image being built by image-builder.  If anything, image builder should make sure those directories are ready to be mounted over.  Am I misunderstanding that approach?  This is related to an issue in CAPI already:

- https://github.com/kubernetes-sigs/cluster-api/issues/2994
- https://github.com/kubernetes-sigs/cluster-api/issues/3064
- https://github.com/kubernetes-sigs/cluster-api/pull/3048

**Comment by moshloop** [comment]
I think this problem is cross-provider - it would be nice to have a solution (or at least interface)  that is agnostic and takes an existing image and converts it into a specific layout

**Comment by voor** [comment]
Just want to chime in on this issue if anybody finds it, with the new support for overriding where images are coming from, I highly encourage an approach that partitions the image **prior** to running it through image builder.  The requirements around partitions are vastly complex.
