### ISSUE TITLE
v1alpha2 - tagging

### ISSUE THREAD

**Issue by timothysc** [kubernetes-sigs/image-builder#31]
Once we feel v1alpha2 of CAP* is in a good state we should tag this repo and point documentation references at this repository.  

/cc @ncdc @detiber @figo @codenrhoden

**Comment by figo** [comment]
good point,  VMware can provide signal through internal testing, community feedback will also key.

**Comment by detiber** [comment]
One thing that I worry about here is that with the current image naming and lookup conventions used (at least by CAPA), that even if we tag the repo for different Cluster API versions the generated images will still be picked up regardless of the Cluster API version in use. Which means if we introduce breaking changes based on consumed version of Cluster API, then there is nothing to prevent their use by the wrong version of Cluster API today.

**Comment by figo** [comment]
When should we start tagging image-builder tool (CAP* part)? it might be right now.
because we are continually making new changes to `master` that potentially can break the tool or break compatibility,  at the same time, we are expecting CAP* users start to consume this tool, then we need tags and versions that been tested.

**Comment by detiber** [comment]
I have no objections to tagging the current state of the repo.

**Comment by codenrhoden** [comment]
My request would be for me to resolve #78 first, which I am working on now.

**Comment by codenrhoden** [comment]
One thing worth discussing -- I had it suggested to me that when we do tag, we do something akin to `v0.1.0-v1alpha2`. The relevant part here being the `v1alpha2`, which I took to signify that the images were intended for CAPI v1alpha2.

To my knowledge, the images produced today are not tied to the CAPI version. Is my understanding incorrect?

If it is, and the image *are* tied to a CAPI version, we will want to start either putting that in the image names, are create a different file structure so that the images are in a folder separated by CAPI version. I just want to clarify this before we tag.

**Comment by detiber** [comment]
I can't speak for the other cluster-api providers, but for AWS, we are currently using the same images for v1alpha1, v1alpha2, and (in development) v1alpha3 releases.

**Comment by figo** [comment]
The OVA only works for CAPV v1alpha2, because CAPV v1alpha1 expecting cloud-init kubeadm exist in image which is not the case any more.

Although technically, we could go back and make change on CAPV v1alpha1 branch to call kubeadm command instead, i don't know whether we want to spend effort on it.

cc @akutz

**Comment by codenrhoden** [comment]
Once #142 goes in, I'd like to tag the repo with `v0.1.0`. With that in place, we can then relay on `git describe` to pull the version during our builds and add it to image metadata.

As of today, images are still not tied to CAP* versions, I don't see a need to add any other version attached to the tag. I'd like to start with 0.1.0. I'm going to open a PR to get the permissions to tag the repo.

/assign
