### ISSUE TITLE
Fix destroying all the folders in the /var/log directory tree

### ISSUE THREAD

**Issue by voor** [kubernetes-sigs/image-builder#314]
We destroy all the folders in the logging directory structure, would much rather do something like this:

`find /var/log/ -type f  -exec rm {} \;` so that we're not trashing folders that certain packages expect to be there, in particular with certain permissions on those folders.

Would change this section, maybe run a shell command prior to it: https://github.com/kubernetes-sigs/image-builder/blob/master/images/capi/ansible/roles/sysprep/tasks/main.yml#L131

**Comment by codenrhoden** [comment]
Agreed. This has been the source of several problems related to audit logging in the past. I know the previous approach was to try and have a "clean slate", but depending on what packages are installed, there could be all kinds of additional folders added and owned by various system uses. Deleting all of `/var/log` nukes all that and it's really kind of impossible to know in advance what to recreate. Some programs have not taken kindly to having their log file deleted at all, and we've had to specifically recreate them.

So rather than `rm`ing them, it almost seems better to truncate.

**Comment by detiber** [comment]
I'm a bit torn on the rm vs truncate thing. I like the idea in concept, but if a process has a file descriptor open to a file that we truncate wouldn't it continue to write to the file afterwards?

**Comment by EleanorRigby** [comment]
[Open FD](https://stackoverflow.com/questions/2028874/what-happens-to-an-open-file-handle-on-linux-if-the-pointed-file-gets-moved-or-d)  will continue to write to file even if the file is deleted (actually, just `unlinked` in Linux).  But if the file is just truncated, I think open FD can definitely write to file.

Are we concerned with what/how much logs are left behind by image building process?

I think to delete every directory under /var/log needs to be fixed. There could be a lot of packages like sysstat, k8s, and, auditd in the future which require log directory recreation and this can become unmanageable.

**Comment by randomvariable** [comment]
I was just testing https://github.com/kubernetes-sigs/image-builder/issues/191 and noticed it's broken on Amazon Linux 2.
