### ISSUE TITLE
Standardise on UEFI for VMware

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/image-builder#391]
In order to enable userdata privacy in Cluster API Provider for vSphere, we would like to leverage vTPMs to encrypt userdata for delivery to the VM. This requires UEFI boot.

#377 serves as POC for UEFI boot of Fedora that the other distros could also leverage.

**Comment by codenrhoden** [comment]
We discussed this a bit during today's office hours. It sounded like a reasonable approach was to add a build-time flag for enabling UEFI instead of the default of bios. There was concern that use of vTPMs is only enabled in a top-tier license enablement, so publishing images with this enabled by default would be problematic. With the flag created, I'm of the mind to continue publishing images with UEFI disabled, and users needing secure boot can build their own image. If enough users are wanting a secure boot enabled image, we would consider publishing a second image with that feature turned on.

How does that approach sound @randomvariable ?

**Comment by randomvariable** [comment]
I wouldn't publish the images with vTPM enabled for the same reason. CAPV downstream could potentially change the VM to enable the vTPM on creation. I think there is however value in UEFI by default given the versions of ESXi and vSphere which are supported?
