### ISSUE TITLE
Feature Suggestion / Discussion: OVA builds: HTTP vs Floppy for kickstart/preseed

### ISSUE THREAD

**Issue by MaxRink** [kubernetes-sigs/image-builder#396]
All OVAs are currently built using the HTTP Server function of packer.
This is not the only way to pass the kickstart-files to packer and causes issues with some implimentations in CI, thus we currently maintain a fork that uses floppy disks to hand the kickstart/preseed-files.

Is there a specific reason why it currently uses HTTP and not directly serves it via floppy that 'm currently overlooking?

**Comment by codenrhoden** [comment]
Max pointed me to this the other day: https://www.packer.io/docs/builders/vmware/vsphere-iso#cdrom-configuration

In conjunction with setting `ks=cdrom:/ks.cfg`. I believe he said it was an easy switch for Ubuntu 20.04, but 18.04 was a bit more difficult. Even if we only switched over 20.04, and found that it worked fine for both Fusion and vCenter based builds, I'd be happy to see that change so that we can unblock OVA CI.

**Comment by moshloop** [comment]
The cloud server images provided for Ubuntu no longer support floppies so I think standardizing on cdrom instead would be better.

**Comment by codenrhoden** [comment]
I'm open to whatever works. It has seemed that there is a difference between 18.04 and 20.04 around this as well.

As for cloud server images, for the OVA builds we start from an installation ISO, not an existing cloud image, so is that important @moshloop? I see them as two different things.

**Comment by moshloop** [comment]
They are 2 different implementations, but there is no reason we can't build a generic mechanism for handling kickstart/preseed.cfg etc across all OS's / Mechanism - Unless there are slight variations between them. We might have a lot of work to do in introducing a more generic mechanism, we shouldn't make it harder for ourselves if it is an either-or situation.

**Comment by kkeshavamurthy** [comment]
I started working on using CDROM instead of HTTP. packer mounts the ks/preseed dirs provided as an ISO image as a second cdrom. When the image is booted on the first cdrom with the OS ISO image is mounted and I was not able to figure out how to mount the second cdrom during boot. If anyone has ideas, it would be appreciated.

I swithed to floppy and was able to get it to work for Ubuntu 18.04 & 20.04 ISO images. Floppy driver support in photon-3 has been recently (Aug 2020) added but the latest ISO available does not have the right kernel version which supports it. 
https://github.com/vmware/photon/issues/1020

I have not tried RHEL but floppy should be supported on it.

**Comment by MaxRink** [comment]
> I started working on using CDROM instead of HTTP. packer mounts the ks/preseed dirs provided as an ISO image as a second cdrom. When the image is booted on the first cdrom with the OS ISO image is mounted and I was not able to figure out how to mount the second cdrom during boot. If anyone has ideas, it would be appreciated.
> 
> I swithed to floppy and was able to get it to work for Ubuntu 18.04 & 20.04 ISO images. Floppy driver support in photon-3 has been recently (Aug 2020) added but the latest ISO available does not have the right kernel version which supports it. @codenrhoden any way we can get a new photon ISO?
> [vmware/photon#1020](https://github.com/vmware/photon/issues/1020)
> 
> I have not tried RHEL but floppy should be supported on it.

yeah, RHEL does still support Floppy.
For Ubuntu and cdrom: you need the new subiquity based installer to work with that (which is cloud-init-based and thus shouldnt even need boot cmds :D), the old one only mounts the first cdrom.
Regarding photon, shouldnt the Rev3 ISOs work ( https://github.com/vmware/photon/wiki/Downloading-Photon-OS )?
