### ISSUE TITLE
pod-infra-container-image missing from kubelet configuration (non-windows)

### ISSUE THREAD

**Issue by dims** [kubernetes-sigs/image-builder#486]
On the windows side, we inject `pod-infra-container-image` when the kubelet starts:
https://cs.k8s.io/?q=pod-infra-container-image&i=nope&files=&repos=kubernetes-sigs/image-builder

The same parameter must be specified in the 10-kubeadm.conf as well:
https://github.com/kubernetes-sigs/image-builder/blob/master/images/capi/ansible/roles/kubernetes/templates/usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf#L3-L4

Note that you will see a warning from kubelet here:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/server.go#L191

However, this parameter is used in the kubelet GC Manager to prevent eviction of the pause image:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/images/image_gc_manager.go#L212-L216

The warning just indicates that if you have an alternate runtime other than docker, you will need to specify it in that runtime's configuration and that kubelet will not be able to do that.

We will be able to avoid issues similar to that logged in https://github.com/kubernetes/kubernetes/issues/81756

**Comment by codenrhoden** [comment]
@dims, so if I understand correctly, we just need to add the `pod-infra-container-image` to the Kubelet config, right?

The link you pasted highlights both `KUBELET_KUBECONFIG_ARGS` and `KUBELET_CONFIG_ARGS`... Looking through the WIndows example, I think this would just be set in `KUBELET_CONFIG_ARGS`, is that right?

**Comment by dims** [comment]
@codenrhoden adding `pod-infra-container-image` to `KUBELET_CONFIG_ARGS` <<< +1

**Comment by dims** [comment]
you can verify if pod-infra-container-image is set properly in kubelet log files. if it is not set properly, you will see the default value for this image (hard coded in kubelet).

**Comment by kkeshavamurthy** [comment]
@dims @codenrhoden 

for non-flatcar OSes, we do not use the kubeadm conf file that dims as linked. We just install kubelet from the k8s repo, which basically installs a vanilla kubelet conf file. 
Should I just edit this config file or does it get manipulated by CAPI later on?

```
root [ /usr/lib/systemd/system ]# cat kubelet.service
[Unit]
Description=kubelet: The Kubernetes Node Agent
Documentation=https://kubernetes.io/docs/
Wants=network-online.target
After=network-online.target

[Service]
ExecStart=/usr/bin/kubelet
Restart=always
StartLimitInterval=0
RestartSec=10

[Install]
WantedBy=multi-user.target
```

**Comment by codenrhoden** [comment]
Hi @kkeshavamurthy. I see what you are talking about, and it took me a bit to tease it all out.

Flatcar aside, right now we have two paths to install Kubernetes (and for this conversation, kubelet). One is installing via package (RPM, DEB), and the other is a raw binary we pull from a URL. We'll need this fix to work in both cases.

When installing from a package, a vanilla systemd unit file does get put in place, as you've pasted above. We do not want to edit this file. The magic happens when we install `kubeadm`. That package adds a drop-in at `/lib/systemd/system/kubelet.service.d/10-kubeadm.conf`, which automatically **overrides** things in the unit file. This file is important, so I'll copy it here:

```ini
# Note: This dropin only works with kubeadm and kubelet v1.11+
[Service]
Environment="KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf"
Environment="KUBELET_CONFIG_ARGS=--config=/var/lib/kubelet/config.yaml"
# This is a file that "kubeadm init" and "kubeadm join" generates at runtime, populating the KUBELET_KUBEADM_ARGS variable dynamically
EnvironmentFile=-/var/lib/kubelet/kubeadm-flags.env
# This is a file that the user can use for overrides of the kubelet args as a last resort. Preferably, the user should use
# the .NodeRegistration.KubeletExtraArgs object in the configuration files instead. KUBELET_EXTRA_ARGS should be sourced from this file.
EnvironmentFile=-/etc/sysconfig/kubelet
ExecStart=
ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS
```

Look familiar? This is the file that exists at https://github.com/kubernetes-sigs/image-builder/blob/master/images/capi/ansible/roles/kubernetes/templates/usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf, which is put in place "manually" when we install via binary instead of a package. So in that scenario, we are re-creating what the package already does for us.

How did I know this file was installed by kubeadm?

```sh
# rpm -qf /lib/systemd/system/kubelet.service.d/10-kubeadm.conf
kubeadm-1.16.11-1.x86_64
```

Since this file is owned by the `kubeadm` package, I would prefer not to modify it either (thought it's option. I think plan B).

Note that the drop-in file also has `EnvironmentFile=-/etc/sysconfig/kubelet`, and it brings in `KUBELET_EXTRA_ARGS`. Since it is the last argument to `kubelet`, it overrides all the others. The comments refer to it as a "last resort", but I think it may be our best option.  It appears to me that we are only installing this file in the URL (binary) scenario. It is done [here](https://github.com/kubernetes-sigs/image-builder/blob/75befb85f76173db374cc13fdfca0e4746c3e6b2/images/capi/ansible/roles/kubernetes/tasks/url.yml#L106-L112).

I propose that we *always* install this file (kubeadm is always looking for it anyways) and that we add the pod eviction parameter there in that template (if we do, and make it a template, please `git mv` the file into `templates`).

A couple things also come to mind. In addition to how @dims mentioned that we can confirm that this is working correctly, we also need to confirm the following:

- [ ] This works for both the binary and package code paths
- [ ] This works for RPM and DEB distros (the "sysconfig" path makes me a bit concerned, as I generally associate that with RPM-based distros and not DEB distros - but if the `kubeadm` DEB package installs an identical `10-kubeadm.conf` that is looking for that file then we are good).

If that sounds like a good path forward, I would give that a shot. I think it's the most clear way to handle all cases. Plan B is just to modify the file put in place by kubeadm the package (and modify our copy of it for the binary install case). That would be the "simpler" way, for sure, but in general it's not good practice to modify files that are owned by packages because it messes with upgrades. For our scenario it wouldn't be a big deal since the images are immutable, but still... The former package maintainer in me cringes at the thought. :)

**Comment by dims** [comment]
Sounds like a great plan @codenrhoden . Cross my fingers!
