### ISSUE TITLE
Windows containerd checksum mismatch when not specifying containerd_sha256

### ISSUE THREAD

**Issue by perithompson** [kubernetes-sigs/image-builder#506]
**What steps did you take and what happened:**
Build windows image with containerd fails when not specifying containerd_sha256 with a checksum mismatch failure

**What did you expect to happen:**
Expected image-builder to have default checksum for containerd set

**Anything else you would like to add:**
There is a containerd_sha256_windows variable available but this is not passed in as an ansible argument.  As the windows variable file overrides Linux during windows build could we go to just one variable and set containerd_sha256 in config/windows/containerd.json and remove the containerd_sha256_windows all together

**Environment:**

Project ([Image Builder for Cluster API](https://github.com/kubernetes-sigs/image-builder/tree/master/images/capi)):

Additional info for Image Builder for Cluster API related issues:

- OS (e.g. from `/etc/os-release`, or `cmd /c ver`): Windows
- Packer Version: 1.6.4
- Packer Provider: vsphere
- Ansible Version: 2.9.11
- Cluster-api version (if using): 
- Kubernetes version: (use `kubectl version`): v1.19.6

/kind bug
/sig windows
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by perithompson** [comment]
@jsturtevant I think this is going to be another one of those, do we need two variables/files conversation but just noticed this and thought id start a discussion before fixing

**Comment by perithompson** [comment]
containerd_url={{user `containerd_url`}} containerd_sha256={{user `containerd_sha256_windows`}} pause_image={{user `pause_image`}} 

Maybe something like this is needed, I guess we need to handle the pause image a little better too as there is containerd_pause_image for Linux that we could merge to just pause image maybe?

**Comment by jsturtevant** [comment]
> containerd_url={{user `containerd_url`}} containerd_sha256={{user `containerd_sha256_windows`}}

This was done in #449.  I think we got burned by this long string in `ansible-args-windows.json` and the difficulties in reviewing it properly since it looks like it was changed in #442.

We had a `containerd_sha256_windows` vs overriding it in the Windows config so we could have the sha's in one file so when versions got bumped it would be obvious to the person updating. I think we should keep go forward with this.

> pause_image={{user pause_image}}

Now that windows pause image is built in k/k (https://github.com/kubernetes/kubernetes/pull/91452) with pause image 3.4.1 we can use a single image reference, so we can use a single variable. But the variable name used by Linux config is `containerd_pause_image` which would be a bit confusing to use as part of the windows kubelet configuration if running docker https://github.com/kubernetes-sigs/image-builder/blob/b72dae811bbb42d7ee03c44c942aa54865eb586e/images/capi/ansible/windows/roles/kubernetes/templates/StartKubelet.ps1#L30 

This was recently addressed for Linux (https://github.com/kubernetes-sigs/image-builder/issues/486) so I think it might be fine align on the single value.  

Could additional things we should probably do:

- add CI for the containerd windows image building 
- come up way to address maintainability of the `ansible-args-*.json` file. Not sure if the linux side runs into issue with it too?

Thoughts?

**Comment by perithompson** [comment]
```
We had a containerd_sha256_windows vs overriding it in the Windows config so we could have the sha's in one file so when versions got bumped it would be obvious to the person updating. I think we should keep go forward with this.
```
This makes total sense to me so I will correct the string in that long variable string and we can save overriding in a file

As for the pause image, I'm confused as to why its called `containerd_pause_image` so maybe @codenrhoden may know, it would be good to align this but I guess it may be this way for a reason. 

I would still love to correct that file but I haven't come up with a way to do that yet. but yes I think CI for containerd windows is going to become more important very soon as more people make the jump

**Comment by perithompson** [comment]
Not sure my PR gives us a direction going forward but at least it allows us to build using the defaults for now

**Comment by codenrhoden** [comment]
With the fixes that have gone in around the containerd checksum and renaming the pause_image variable, I think this can be closed?

**Comment by perithompson** [comment]
Yep I think you're right, we can close this out!
