### ISSUE TITLE
Generic version of debug-tools for executables

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/image-builder#518]
**Is your feature request related to a problem? Please describe.**

feature - for windows, we need executables for CSI, CNI, and so on that are hollow , i.e. not really aware of cni or csi, but just, copying executables installed to image

**Describe the solution you'd like**

- Add an ansible step "cni-executables-install/" OR
- Add an ansible step "additional-file-copy/" 

**Describe alternatives you've considered**

- Make a container and unzip it at runtime 
- post kubeadm wget actions yuck !

**Additional context**

@perithompson and me want to ship Antrea in windows images ! 

/kind feature

**Comment by jsturtevant** [comment]
A little background... Since windows doesn't have privileged containers it can't easily install and run services from pods like Linux does.  sig-windows came up with some work arounds using hostnetwork for Windows and Docker but it doesn't work as well with Containerd: https://github.com/kubernetes-sigs/sig-windows-tools/issues/128#issuecomment-744840966

For now with Containerd, in the current state of things it is necessary for containerd builds to have the CNI running on the node.  This will be temporary once [privileged containers](https://github.com/kubernetes/enhancements/pull/2288) lands and matures (which would make it closer to the way Linux install and run CNI's)

If this could be designed to be generic to install not just Antrea that would be beneficial for capz as well.

**Comment by perithompson** [comment]
Completely agree with this, we were thinking as a generic way to do this, we could just start with a way to download a variable list of executables into a folder for CSI/CNI etc and let cluster API do the actual installation step? Any thoughts? I think maintaining an installation routine for each cni would be to hard to maintain...

**Comment by jsturtevant** [comment]
Agreed,  Linux does something similar for the base line cnis: https://github.com/kubernetes-sigs/image-builder/blob/0b97b19a856ac257c4139b16eda76d1d43b72499/images/capi/ansible/roles/kubernetes/tasks/url.yml#L36

The tricky part might be setting up the configuraiton between containerd/CNI/kubelet.

**Comment by jayunit100** [comment]
im ok w ANY solution here, generic or CNI specific , but feel like generic gives max flexibility to vendors w/o making upstream opinionated
