### ISSUE TITLE
imgpkg / bundle  / http facade awareness for image builds 

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/image-builder#571]
**Is your feature request related to a problem? Please describe.**

For windows nodes, you need to build an OVA from scratch - and can't borrow OVAs from elsewhere.    Thus anyone using CAPI w/ windows need to use image builder to create their images, for their nodes.

This means that the UX around how binaries are pulled into image builder needs to be dumbed down a little, since its not just cloud providers building image builder into their internal workflows - but rather - end users wanting to get a cluster up quickly.

*problem* :when we build windows images, we pull artifacts from a URL, we force users to *host* their windows kubelet/kubeproxy/containerd/hcsshim/... from an endpoint.  USers may not have a good way to host this stuff or may not have an internal process that allows for this.  

- ... One really clean and scalable way to host files as docker images is https://carvel.dev/imgpkg/, which suggests an automatic mechanism for creating a hosted package of imagbuilder windows binaries.... 
- another option would be to make imagebuilder capable of reading files from a local disk somehow, using something like scp to put them onto an image

However, imgpkg doesnt "serve" the files on an endpoint, but rather, directly copies them as a folder to a destination.

So, i  would like a way to consume from files, rather then a url.... 

**Describe the solution you'd like**

1) Can we make it so that an `imgpkg` aware hosting command in image builder, i.e. one which runs:

```
imgpkg pull -i index.docker.io/periismyfriend/windowz:v1 --output /tmp/my-windows-exes
python3 -m http.server
```

for users, that way we can give folks a very clean image building experience, wherein they only need to provide a docker registry of a `imgpkg` repo as the input to image builder.  This would mean users dont need to host there own windows executables on a port... instead, the VM that is building the image could just pull down its bits from the imagebuilder node.

2) IF we're not able to bundle imgpkg awareness, can we modify the way we invoke imgbuilder so that it copys executables from its local disk to the ova somehow , rather then doing a pull from a URL ? 

**Describe alternatives you've considered**

Make a third artifact that connects imgpkg artifacts with imagebuilder execution, i.e. a init container which ran image builder in a pod, pulled the artifacts into a PV/hostpath , and invoked image builder on an endpoint .  this however would only work in k8s 

**Additional context**

/kind feature

**Comment by jayunit100** [comment]
so as an alternative i filed https://github.com/ansible/ansible/issues/74059 , just as an idea - make it so that note that `get_file` and `win_get_file` are ultimately same underlying module in ansible, so modifying the semantics of the main one implies updating the windows specific use case as well, 

hence, i only filed this for the `get_file` since that is good enough to cascade the solution to this problem for windows.

**Comment by codenrhoden** [comment]
I'm thinking about this with three different lenses/use-cases...

1. Users are building pure upstream-only images
  - In this case, I don't think we want to introduce any dependence on anything other than what is published by the K8s project itself.
2. Uses are are building pure upstream, but want to add some additional customization (really, the heart of what image-builder enables)
  - I think this looks similar to (1), and if you want to make customizations, you rely on the existing extension points
  - THis would be things like the custom roles, the existing `additional_prepull_images` for Windows, and enhancements like https://github.com/kubernetes-sigs/image-builder/pull/529 that allow you to load additional containers and executables from network-reachable URLs and registries
3. Users are building images that include custom (downstream) components that *replace* upstream ones. For example, if you decide to compile K8s yourself, how do you load that into your image?
  - Thus far, we've wanted to rely on a common set of install steps for this scenario that very closely mirror the setup for upstream components. That way even if we don't know *what* was installed, we have a good feeling of *how* it was installed.
  - In order to achieve this, it is on this downstream consumer to create a setup that either hosts OS packages (RPM, DEB), or tar files that contain executables and container images much like the K8s project publishes binaries that are consumable from CI (but not published as packages).

I would be concerned in scenario #3 of creating a third codepath for installations, especially since our current roles that installed K8s, containerd, etcd, are not skippable. You *must* provide a valid package/http based installation source because that's what the K8s project makes consumable. What are the components within the Windows node scenario that don't have this equivalent? If there are items that users wish to install that are outside of the project's core artifacts, that's what the custom roles and extension points are for.

I'm sure I'm over simplifying all of this, so I'm happy to chat more so that I understand.
