### ISSUE TITLE
capi image: docker image support

### ISSUE THREAD

**Issue by Sn0rt** [kubernetes-sigs/image-builder#74]
for some reason, some users want to use docker as runtime.

and now I have try to use  `geerlingguy.docker` to build a new image, only AMI, for k8s runtime.

and it's working fine. 

can we consider to support CAPI docker runtime?

```
$ kubectl  --kubeconfig guohao4  get node -o wide --all-namespaces
NAME                                       STATUS   ROLES    AGE     VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION    CONTAINER-RUNTIME
ip-10-0-0-114.us-east-2.compute.internal   Ready    <none>   3m13s   v1.15.4   10.0.0.114    <none>        Ubuntu 18.04.3 LTS   4.15.0-1051-aws   docker://19.3.3
ip-10-0-0-144.us-east-2.compute.internal   Ready    master   7m38s   v1.15.4   10.0.0.144    <none>        Ubuntu 18.04.3 LTS   4.15.0-1051-aws   docker://19.3.3
ip-10-0-0-217.us-east-2.compute.internal   Ready    master   5m28s   v1.15.4   10.0.0.217    <none>        Ubuntu 18.04.3 LTS   4.15.0-1051-aws   docker://19.3.3
ip-10-0-0-64.us-east-2.compute.internal    Ready    master   5m44s   v1.15.4   10.0.0.64     <none>        Ubuntu 18.04.3 LTS   4.15.0-1051-aws   docker://19.3.3
```

**Comment by moshloop** [comment]
According to [sig-node](https://kubernetes.slack.com/archives/C0BP8PW9G/p1561135308262200?thread_ts=1561110820.257500&cid=C0BP8PW9G), containerd is not officially supported by upstream, so more than adding support for docker, I think we should make it the default.

**Comment by detiber** [comment]
sig-node has tests that they run for [containerd](https://testgrid.k8s.io/sig-node-containerd), [cri-o](https://testgrid.k8s.io/sig-node-cri-o), and [docker](https://testgrid.k8s.io/sig-node-docker)...

I hesitate to make docker the default, since there have been known issues between supported docker versions and kubelet versions, which means we'd have to track compat between the two and ensure the right versions are installed based on the right kubernetes versions being installed.

In comparison containerd/cri-o use goes through the CRI interface rather than the docker-shim, which provides much better assurances of compatibility when version skew between the kubelet and the runtime is at play.

**Comment by moshloop** [comment]
If I look at the release notes: https://kubernetes.io/docs/setup/release/notes/#unchanged there are specific versions of docker listed, but no mention of containerd or cri-o - Maybe the release notes need to be updated?

**Comment by randomvariable** [comment]
Recommend we close this? dockershim code is being removed AFAIK?

**Comment by dims** [comment]
/close

yes!!
