### ISSUE TITLE
Implement etcd network prioritization in images

### ISSUE THREAD

**Issue by josh-ferrell** [kubernetes-sigs/image-builder#846]
**Is your feature request related to a problem? Please describe.**
etcd can experience network congestion when the leader is receiving a high number of client requests. 

**Describe the solution you'd like**
We should implement the recommended prioritization for peer traffic using traffic control or a similar mechanism. 

**Additional context**
[etcd Network tuning recommendations](https://github.com/etcd-io/etcd/blob/a621d807f061e1dd635033a8d6bc261461429e27/Documentation/tuning.md#network)

/kind feature

**Comment by josh-ferrell** [comment]
I agree that is does seem more specific to the control planes but I'm not sure where tuning should live from a lifecycle perspective if it affects Kubernetes as a whole. Does it make more sense that this is done as a function of control plane initialization like `kubeadm init`?

Looping in @randomvariable in case there is more history or feedback needed I'm not aware of.

**Comment by randomvariable** [comment]
The tuning will be for ports reserved for etcd, so it's reasonable to do in the image I think. This would be best done using udev rules on all ethernet devices.

**Comment by codenrhoden** [comment]
> The tuning will be for ports reserved for etcd, so it's reasonable to do in the image I think.

That seems to be the case here. It's not like there are other traffic prioritization rules that it will be competing with.


> This would be best done using udev rules on all ethernet devices.

So you are saying have this happen automatically for all devices, rather than just using `tc` directly. Makes sense we don't know what all the devices will be ahead of time.


> I agree that is does seem more specific to the control planes but I'm not sure where tuning should live from a lifecycle perspective if it affects Kubernetes as a whole. Does it make more sense that this is done as a function of control plane initialization like kubeadm init?

I doubt this one is better with `kubeadm init`, but yeah, I was definitely thinking more broadly wondering what we should do as more optimizations are possible for control plane vs worker nodes. Do we try to push some of that to `kubeadm`? Or is the answer to eventually split images into two "flavors" of image? There's hasn't been a lot of discussion along those lines.
